---
# tasks file for deploy_apache
# tasks file for deploy_apache
- name: Install default Apache Web Server
  apt:
    name: apache2
    state: latest

- name: Start Apache and Enable it on every boot
  service:
    name: apache2
    state: started
    enabled: yes

